{
  config,
  lib,
  self,
  pkgs,
  ...
}:
let
  cfg = config.pm-modules;
  inherit (lib) mkIf mkOption;
  inherit (lib.types) bool;
in
{
  config = mkIf cfg.stylix.enable {
    stylix = {
      enable = true;
      polarity = "dark";
      image = "${self}/misc/wallpaper.jpg";
      # base16Scheme = "${pkgs-unstable.base16-schemes}/share/themes/0x96f.yaml";
      base16Scheme = "${pkgs.base16-schemes}/share/themes/default-dark.yaml";
      # base16Scheme = ../misc/dark_plus_custom.yaml;
      # base16Scheme = {
      #   "scheme" = "OneDarker";
      #   "author" = "guill (based on 256-color onedark.vim)";
      #   "base00" = "262626";
      #   "base01" = "303030";
      #   "base02" = "3a3a3a";
      #   "base03" = "5f5f5f";
      #   "base04" = "444444";
      #   "base05" = "afafaf";
      #   "base06" = "abb2bf";
      #   "base07" = "c8ccd4";
      #   "base0A" = "d75fd7";
      #   "base09" = "d7875f";
      #   "base08" = "ff5f87";
      #   "base0B" = "87d787";
      #   "base0C" = "56b6c2";
      #   "base0D" = "00afff";
      #   "base0E" = "d7af87";
      #   "base0F" = "be5046";
      # };
      # base16Scheme = {
      #   "scheme" = "Dark Plus Tinted";
      #   "author" = "Generated by ChatGPT";
      #   "base00" = "1e1e1e"; # background (dark_gray2)
      #   "base01" = "282828"; # lighter bg (dark_gray3)
      #   "base02" = "404040"; # selection bg / subtle highlights (dark_gray4)
      #   "base03" = "858585"; # comments / faded text (dark_gray)
      #   "base04" = "c6c6c6"; # dim fg (light_gray2)
      #   "base05" = "d4d4d4"; # default fg (light_gray)
      #   "base06" = "eeeeee"; # light fg (light_gray3)
      #   "base07" = "ffffff"; # white
      #   "base08" = "ff1212"; # red
      #   "base09" = "ce9178"; # orange
      #   "base0A" = "d7ba7d"; # gold
      #   "base0B" = "6a9955"; # green
      #   "base0C" = "75beff"; # aqua / cyan
      #   "base0D" = "569cd6"; # blue
      #   "base0E" = "6796e6"; # purple-ish blue
      #   "base0F" = "f14c4c"; # orange-red (extra warning)
      # };
      fonts = {
        sansSerif = {
          package = pkgs.fira-sans;
          name = "Fira Sans";
        };
        serif = config.stylix.fonts.sansSerif;
        monospace = {
          package = pkgs.nerd-fonts.fira-mono;
          name = "Fira Mono";
        };
      };
    };
  };
  options.pm-modules.stylix.enable = mkOption {
    type = bool;
    default = cfg.enableDefault;
    description = ''
      use stylix to style the system
    '';
  };
}
